### ISSUE TITLE
Column1 not found

### ISSUE THREAD

**Issue by FrancistheDog** [kerski/power-query-sharepoint-faster-easier#1]
I would like to create a dataflow via power query online.  When i rebuild I get the following error.  The column 'Column1' of the table wasn't found.  Any ideas?

**Comment by kerski** [comment]
Do you get that error with fnGetFields or fnGetSharePointData?  Also,  did you copy the m code from the dataset to the dataflow?  I have found that method wraps more code around the function automatically (guess something MSFT does in the background).  I typically have to copy the text of the code in the advanced editor over to the dataflow.

**Comment by kerski** [comment]
Could you download the latest release, and try? I believe the issue you had was where the SharePoint list was empty.
